name: Google Search Tests Using Selenium

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Chrome WebDriver
        run: |
          CHROMEDRIVER_URL="https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.92/linux64/chromedriver-linux64.zip"
          curl -sS "$CHROMEDRIVER_URL" > /tmp/chromedriver.zip
          unzip -q /tmp/chromedriver.zip -d /tmp/
          chmod +x /tmp/chromedriver
          sudo mv /tmp/chromedriver /usr/local/bin/

      - name: Build and test with Maven
        run: |
          echo "headless=true" >> $GITHUB_ENV
          mvn clean test

